github: [andrea-mariadb-2, andrea_mariadb, andipandi111, 777ninjamusic]
patreon: andrea_mariadb
open_collective: andrea_mariadb
ko_fi: # Replace with a single Ko-fi username
tidelift: npm-andrea_mariadb
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: andrea-mariadb-2
otechie: andrea-mariadb
custom: ['https://www.youtube.com/channel/UCuoDzKdqTwXtJe5kwo4tNYQ', 'https://www.youtube.com/channel/UCeTsecOxtD8zuDKPpcL9crg', 'https://www.youtube.com/channel/UCzTBP3CKnn_Pfn9x1ESaOZA']
